version: 2.1
jobs:
  lint:
    docker:
      - image: cryptogarageinc/elements-testing:v0.18.1.3

    steps:
      - checkout
      - run: npm run tslint_check

  build:
    docker:
      - image: cryptogarageinc/elements-testing:v0.18.1.3
    steps:
      - checkout
      - run: npm install
      - run: npm run cmake_all
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cryptogarageinc/elements-testing:v0.18.1.3
    steps:
      - attach_workspace:
          at: .
      - run: npm run test_report
      - store_test_results:
          path: ./reports/jest
      - store_artifacts:
          path: ./reports/jest

  integration:
    docker:
      - image: cryptogarageinc/elements-testing:v0.18.1.3
    steps:
      - attach_workspace:
          at: .
      - run: ./integration_tests/__tests__/start-bitcoind.sh $(pwd) 'integration_tests'
      - run: sleep 1
      - run: npm run test_integration
      - store_artifacts:
          path: ./build_coverage/lcov_cfddlc_output
          destination: raw-test-output
      - store_test_results:
          path: ./reports/integration
      - store_artifacts:
          path: ./reports/integration

workflows:
  version: 2.1
  lint-build-test-integration:
    jobs:
      - lint
      - build
      - test:
          requires:
            - build
      - integration:
          requires:
            - build
